apiVersion: apps/v1
kind: Deployment
metadata:
  name: magellan-app-stable
  labels:
    app: magellan-app
    version: stable
spec:
  replicas: 3
  selector:
    matchLabels:
      app: magellan-app
      version: stable
  template:
    metadata:
      labels:
        app: magellan-app
        version: stable
    spec:
      containers:
      - name: magellan-app
        image: your-search-app:latest # Stable image
        ports:
        - containerPort: 80
